"""Exact supported block-probability search for `ultra`.

For a conditional block unitary ``U_b(xi)``, the Pauli-projected block channel
can be written directly from the Pauli expansion coefficients of the unitary:

    U_b(xi) = sum_P u_P(xi) P,
    q_{b,P}(xi) = |u_P(xi)|^2,
    u_P(xi) = 2^{-n} Tr[P U_b(xi)].

This avoids the much more expensive path of:

- evaluating the full retained diagonal over all ``4^n`` basis Paulis,
- then performing a full Walsh inversion.

The crucial extra structure for the env model is that each segment generator is
a sum of commuting Pauli strings. Therefore each segment unitary has an exact
sparse Pauli expansion, and a whole block can be built by repeated sparse
Pauli-amplitude convolution. This avoids the dense block-unitary construction
entirely.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .pauli import SignedPauliTerm, multiply_pauli_strings
from .segment_generators import SegmentGenerator
from .block_partition import BlockDescriptor


@dataclass(frozen=True)
class SupportedBlockProbabilitySearch:
    """Exact block probabilities searched on the generated Pauli subgroup."""

    block: BlockDescriptor
    xi: float
    generator_rank_bound: int
    candidate_support_size: int
    probabilities: dict[str, float]


def build_supported_block_probability_search(
    *,
    block: BlockDescriptor,
    xi_value: float,
    segment_generators: tuple[SegmentGenerator, ...],
) -> SupportedBlockProbabilitySearch:
    """Compute exact block probabilities by sparse Pauli-amplitude propagation."""

    amplitudes = build_block_pauli_amplitudes(
        block=block,
        xi_value=xi_value,
        segment_generators=segment_generators,
    )
    probabilities = {
        pauli_string: float(np.abs(amplitude) ** 2)
        for pauli_string, amplitude in amplitudes.items()
        if np.abs(amplitude) ** 2 > 1e-14
    }
    total_probability = sum(probabilities.values())
    if total_probability <= 0.0:
        raise ValueError("Sparse block-amplitude propagation found zero total probability.")
    probabilities = {
        pauli_string: probability / total_probability
        for pauli_string, probability in sorted(probabilities.items())
    }
    return SupportedBlockProbabilitySearch(
        block=block,
        xi=xi_value,
        generator_rank_bound=_count_distinct_block_labels(
            block=block,
            segment_generators=segment_generators,
        ),
        candidate_support_size=len(amplitudes),
        probabilities=probabilities,
    )


def build_block_pauli_amplitudes(
    *,
    block: BlockDescriptor,
    xi_value: float,
    segment_generators: tuple[SegmentGenerator, ...],
) -> dict[str, complex]:
    """Build the exact Pauli expansion amplitudes of a block unitary.

    Because each segment generator is a sum of commuting Pauli strings, each
    segment unitary can be expanded exactly as a sparse Pauli dictionary. The
    block unitary is then the ordered product of those segment dictionaries.
    """

    if not segment_generators:
        raise ValueError("segment_generators must not be empty.")
    num_qubits = len(segment_generators[0].terms[0].pauli_string)
    amplitudes: dict[str, complex] = {"I" * num_qubits: 1.0 + 0.0j}

    for segment_index in range(block.start_segment, block.end_segment + 1):
        segment = segment_generators[segment_index]
        segment_amplitudes = _build_segment_pauli_amplitudes(segment, xi_value=xi_value)
        amplitudes = _convolve_pauli_amplitudes(left=segment_amplitudes, right=amplitudes)

    return _prune_small_amplitudes(amplitudes)


def enumerate_generated_block_paulis(
    *,
    block: BlockDescriptor,
    segment_generators: tuple[SegmentGenerator, ...],
) -> tuple[str, ...]:
    """Enumerate the Pauli subgroup generated by distinct labels in one block."""

    block_labels = []
    for segment_index in range(block.start_segment, block.end_segment + 1):
        for term in segment_generators[segment_index].terms:
            if "I" * len(term.pauli_string) == term.pauli_string:
                continue
            block_labels.append(term.pauli_string)

    if not block_labels:
        identity = "I" * len(segment_generators[block.start_segment].terms[0].pauli_string)
        return (identity,)

    generators = tuple(sorted(set(block_labels)))
    support = {("I" * len(generators[0]))}
    for generator in generators:
        expanded = set(support)
        for pauli_string in support:
            _, product_label = multiply_pauli_strings(pauli_string, generator)
            expanded.add(product_label)
        support = expanded
    return tuple(sorted(support))


def _build_segment_pauli_amplitudes(
    segment: SegmentGenerator,
    *,
    xi_value: float,
) -> dict[str, complex]:
    """Build the exact Pauli amplitudes of one commuting segment unitary."""

    signed_counts = _compress_signed_counts(segment.terms)
    num_qubits = len(segment.terms[0].pauli_string)
    amplitudes: dict[str, complex] = {"I" * num_qubits: 1.0 + 0.0j}

    for pauli_string, signed_count in sorted(signed_counts.items()):
        theta = xi_value * segment.duration * signed_count
        factor = {
            "I" * num_qubits: complex(np.cos(theta), 0.0),
            pauli_string: -1.0j * np.sin(theta),
        }
        amplitudes = _convolve_pauli_amplitudes(left=factor, right=amplitudes)

    return _prune_small_amplitudes(amplitudes)


def _compress_signed_counts(terms: tuple[SignedPauliTerm, ...]) -> dict[str, int]:
    """Compress repeated Pauli labels into a signed multiplicity map."""

    signed_counts: dict[str, int] = {}
    for term in terms:
        if all(letter == "I" for letter in term.pauli_string):
            continue
        signed_counts[term.pauli_string] = signed_counts.get(term.pauli_string, 0) + term.sign
    return {pauli_string: count for pauli_string, count in signed_counts.items() if count != 0}


def _convolve_pauli_amplitudes(
    *,
    left: dict[str, complex],
    right: dict[str, complex],
) -> dict[str, complex]:
    """Multiply two Pauli-expansion dictionaries exactly."""

    amplitudes: dict[str, complex] = {}
    for left_label, left_amplitude in left.items():
        for right_label, right_amplitude in right.items():
            phase, product_label = multiply_pauli_strings(left_label, right_label)
            amplitudes[product_label] = amplitudes.get(product_label, 0.0 + 0.0j) + (
                left_amplitude * right_amplitude * phase
            )
    return amplitudes


def _prune_small_amplitudes(amplitudes: dict[str, complex]) -> dict[str, complex]:
    """Drop numerical noise from an amplitude dictionary."""

    return {
        pauli_string: amplitude
        for pauli_string, amplitude in amplitudes.items()
        if abs(amplitude) > 1e-14
    }


def _count_distinct_block_labels(
    *,
    block: BlockDescriptor,
    segment_generators: tuple[SegmentGenerator, ...],
) -> int:
    """Return the number of distinct non-identity Pauli labels in one block."""

    labels = set()
    for segment_index in range(block.start_segment, block.end_segment + 1):
        for term in segment_generators[segment_index].terms:
            if all(letter == "I" for letter in term.pauli_string):
                continue
            labels.add(term.pauli_string)
    return len(labels)
